name: Checkstyle and Format

on:
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code with Checkstyle
        uses: actions/checkout@v4

      - name: Run Checkstyle
        id: checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
        
      - name: Check if Checkstyle passed
        run: |
          if grep -q '::warning' <<<"$(cat /github/workflow/logs/1.json)"; then
            echo "Checkstyle issues detected."
            echo "checkstyle_failed=true" >> $GITHUB_ENV
          else
            echo "No Checkstyle issues found."
            echo "checkstyle_failed=false" >> $GITHUB_ENV
          fi

  
  format:
    runs-on: ubuntu-latest
    needs: checkstyle
    if: ${{ env.checkstyle_failed  == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}